#!/bin/sh

# this makes it work in Ubuntu
xhost +

## you might need to append the TTY you are working on
xinit

wmname LG3D

# Remap caps lock to left control. This is not strictly speaking
# exwm related, but it's handy
setxkbmap -option 'ctrl:no caps'

# Set fallback cursor
xsetroot -cursor_name left_ptr

# If Emacs is started in server mode, `emacsclient` is a convenient way to edit
# files in place (used by e.g. `git commit`)
export VISUAL=emacsclient
export EDITOR="$VISUAL"

xrandr --dpi 218

GDK_SCALE=2
GDK_DPI_SCALE=0.5
QT_FONT_DPI=96

# Finally launch emacs and enable exwm
exec dbus-launch --exit-with-session emacs -f exwm-enable --eval "(exwm-enable)"
