#!/bin/bash

# down and right to control
# Trick to get it work with the modifiers
xmodmap -e "keycode 114 = Control_L Right"
xmodmap -e "keycode 116 = Control_L Down"

# Switch the modifiers keys
xmodmap -e "clear lock"
xmodmap -e "add control = Down"
xmodmap -e "add control = Right"

# In case of using a logitech mac keyboard in linux
# keycode 49 = less greater less greater backslash backslash backslash
# keycode 94 = section degree section degree U2032 U2033 U2032

# clear mod4
# clear mod1

# keycode 133 = Alt_L NoSymbol Alt_L
# keycode 64 = Super_L NoSymbol Super_L
# keycode 134 = ISO_Level3_Shift NoSymbol ISO_Level3_Shift
# keycode 108 = Super_R NoSymbol Super_R
# keycode 66 = Control_L NoSymbol Control_L

# add mod1 = Alt_L
# add mod4 = Super_L
# add control = Control_L
